#!/usr/bin/env python3
"""Master report runner — executes all briefs, produces consolidated summary."""
import importlib.util, sys
from datetime import date
from pathlib import Path

REPORTS_DIR = Path("/home/executive-workspace/reports")
OUTPUT_DIR = Path(f"/home/executive-workspace/reports/output/{date.today()}")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

BRIEFS = ["daily_brief", "financial_brief", "tech_brief"]

def load_and_run(name):
    spec = importlib.util.spec_from_file_location(name, REPORTS_DIR / f"{name}.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.main()

def main():
    sections = []
    for brief in BRIEFS:
        try:
            print(f"Running {brief}...")
            content = load_and_run(brief)
            sections.append(content)
        except Exception as e:
            sections.append(f"# {brief} — FAILED\n\n_Error: {e}_\n")
            print(f"❌ {brief} failed: {e}")

    consolidated = f"# 📋 Consolidated Daily Report — {date.today()}\n\n---\n\n"
    consolidated += "\n---\n\n".join(sections)
    consolidated += f"\n---\n\n_Generated by Jarvis reporting pipeline_\n"

    out = OUTPUT_DIR / "consolidated_report.md"
    out.write_text(consolidated)
    print(f"\n✅ Consolidated report: {out}")

if __name__ == "__main__":
    main()
